# Generated by Django 6.0.6 on 2026-06-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_options_alter_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='restaurantinfo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={},
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('confirmed', 'Подтверждена'), ('cancelled', 'Отменена')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='seats',
            field=models.PositiveIntegerField(),
        ),
    ]
